#!/bin/bash

#=======================================================================================
#title:		ut_install
#description:	This script gets this utility package contents and setup in your system.
#author:	gilbertolptn
#usage:		curl -s https://raw.githubusercontent.com/gilbertolptn/bashutils/master/utctrl_install | sh -
#notes:		You need package git installed
#=======================================================================================

function printcolor {
	printf "\033[0;36m$1\033[0m\n"
}

# Config
mainfolder=~/.bashutils
scriptfolder=scripts

#Prepare
if [ -x "$mainfolder/$scriptfolder" ]; then
	rm -rf "$mainfolder/$scriptfolder"
	printcolor "Updating folder [$mainfolder] in your home folder..."
else
	printcolor "Creating folder [$mainfolder] in your home folder..."
fi;
mkdir -p "$mainfolder"
cd "$mainfolder"

#Get scripts
printcolor "Get contents from github..."
git clone https://github.com/gilbertolptn/bashutils/ $scriptfolder

# Path
printcolor "Updating ~/.bashrc with a new Path..."

# Remove old configuration
sed -i '/#bashutils_linecontrol/d' ~/.bashrc

# Add new configuration
echo "# Path to bashutils installed by https://github.com/gilbertolptn/bashutils/utctrl_install #bashutils_linecontrol" >> ~/.bashrc
echo "# These lines are controled by bashutils (un)install. Please dont remove manually.        #bashutils_linecontrol" >> ~/.bashrc
echo "if [ -d \""$mainfolder/$scriptfolder"\" ] ; then                                          #bashutils_linecontrol" >> ~/.bashrc
echo "    PATH=\"\$PATH:$mainfolder/$scriptfolder/\"                                 #bashutils_linecontrol" >> ~/.bashrc
echo "fi                                                                                        #bashutils_linecontrol" >> ~/.bashrc

printcolor "-----------------------------------------------------------------------------------"
printcolor ""
printcolor "Installation Complete!"
printcolor ""
printcolor "You can use typing 'ut'... Because all scripts starting with the 'ut' prefix... Try :) "
printcolor "Ex.: ut_list"
printcolor ""
printcolor "PS: Maybe you need run a new shell/terminal to take effect the new PATH..."
printcolor "-----------------------------------------------------------------------------------"
