#!/bin/bash

#=======================================================================================
#title:		ut_list
#description:	This script list all the scripts in this set.
#author:	gilbertolptn
#usage:		utlist
#=======================================================================================

function printcolor {
	printf "\033[0;36m$1\033[0m\n"
}

# Config
scriptfolder=~/.bashutils/scripts

printcolor
printcolor "ut - Bash Utils - Avaliable Commands:"
printcolor

for file in `ls $scriptfolder | egrep -v 'LICENSE|README.md'`; do
	printcolor "------------------------------------------------------------------------"
	cat $scriptfolder/$file | egrep '#title|#description|#usage|#notes' | egrep -v 'egrep'
done;

printcolor "------------------------------------------------------------------------"

