#!/bin/bash

#=======================================================================================
#title:		utctrl_install
#description:	This script gets this utility package contents and setup in your system.
#author:	gilbertolptn
#usage:		curl -s https://raw.githubusercontent.com/gilbertolptn/bashutils/master/utctrl_install | sh -
#notes:		You need package git installed
#=======================================================================================

function printcolor {
	printf "\033[0;36m$1\033[0m\n"
}

# Config
scriptfolder=~/.bashutils/github

#Prepare
if [ -x $scriptfolder ]; then
#	rm -rf $scriptfolder
	printcolor "Updating folder [$scriptfolder] in your home folder..."
else
	printcolor "Creating folder [$scriptfolder] in your home folder..."
fi;
mkdir -p "$scriptfolder"
cd "$scriptfolder"

#Get scripts
printcolor "Get contents from github..."
git clone https://github.com/gilbertolptn/bashutils/

# Path
printcolor "Updating ~/.bashrc with a new Path..."

# Remove old configuration
sed -i '/#bashutils_linecontrol/d' ~/.bashrc

# Add new configuration
echo "" >> ~/.bashrc
echo "# Path to bashutils installed by https://github.com/gilbertolptn/bashutils/utctrl_install #bashutils_linecontrol" >> ~/.bashrc
echo "# These lines are controled by bashutils (un)install. Please dont remove manually.        #bashutils_linecontrol" >> ~/.bashrc
echo "if [ -d \""$scriptfolder"\" ] ; then                                          #bashutils_linecontrol" >> ~/.bashrc
echo "    PATH=\"\$PATH:$scriptfolder/bashutils/\"                                 #bashutils_linecontrol" >> ~/.bashrc
echo "fi                                                                                        #bashutils_linecontrol" >> ~/.bashrc

printcolor "Complete!"
printcolor ""
printcolor "-----------------------------------------------------------------------------------"
printcolor ""
printcolor "You can use typing 'ut'... Because all scripts having the 'ut' prefix... Try :) "
printcolor ""
printcolor "Ex.: Try type: utlist"
printcolor ""
printcolor "-----------------------------------------------------------------------------------"

#Update the PATH to avoid restart to use
printcolor "Running a new shell to take effect the new PATH..."
exec /bin/bash

