#!/bin/bash

#==============================================================================
#title:		utiptablesclear
#description:	This script clear all rules and policies from iptables.
#author:	gilbertolptn
#usage:		utiptablesclear
#notes:		Needs root.
#==============================================================================

function printcolor {
	printf "\033[0;36m$1\033[0m\n"
}

printcolor "Cleaning all rules from iptables"

sudo iptables -F
sudo iptables -X
sudo iptables -t nat -F
sudo iptables -t nat -X
sudo iptables -t mangle -F
sudo iptables -t mangle -X
sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT

printcolor "Complete"
